### ISSUE TITLE
Documentation updated to add instructions for specifying the Paimon temporary directory.

### ISSUE THREAD

**Issue by zhengxingmao** [apache/paimon-trino#12]
**Documentation updated to add instructions for specifying the Paimon temporary directory.**
https://github.com/apache/incubator-paimon/blob/f8eb4d9d8f9792aba3798a696cbd7721d187cae2/paimon-common/src/main/java/org/apache/paimon/plugin/PluginLoader.java#L70
https://github.com/apache/incubator-paimon/blob/f8eb4d9d8f9792aba3798a696cbd7721d187cae2/paimon-common/src/main/java/org/apache/paimon/plugin/PluginLoader.java#L143

**Comment by JingsongLi** [comment]
Already no temporary dir now.
